project:
  type: website
  output-dir: docs

website:
  title: "Praise & Glory"
  navbar:
    left:
      - text: Study 1
        href: study-1.qmd
      - text: Study 2
        href: study-2.qmd
    right:
      - icon: house-door
        href: index.qmd
  page-footer:
    left: |
      &copy; C.O.
    right: |
      Made with ❤️ in Richmond, Virginia
        
format:
  html:
    theme: simplex
    css: styles.css



